<?php
/** @var Magento\Backend\Block\Template $block */
/** @var MatseVH\Repeater\Block\Adminhtml\Widget\Repeater\AbstractField $field */
$field     = $block->getField();
$elementId = $block->getElementId();
?>
<textarea type="text"
    id="<?= $escaper->escapeHtmlAttr($elementId) ?>_<?= $escaper->escapeHtmlAttr($field->getName()) ?>_{{idx}}"
    class="input-text admin__control-textarea<?= $field->isRequired() ? ' required-entry' : '' ?>"
    data-field="<?= $escaper->escapeHtmlAttr($field->getName()) ?>"
    <?= $field->isRequired() ? 'required="true"' : '' ?>>{{value}}
</textarea>
